### ISSUE TITLE
WrapAction does not respect hard wrap setting

### ISSUE THREAD

**Issue by mgartner** [abrookins/WrapToColumn#46] opened 2021-08-10 22:37 UTC
Thanks for fixing #40!

As of version `1.6.0-SNAPSHOT`, the `WrapAction` no longer respects the "Hard wrap at" setting. I'm not sure if the fix for #40 broke this, or if it was some other change.

#### Example

Both comment paragraphs had the `WrapAction` applied to them. The vertical line is at the 80-character hard wrap limit.

![image](https://user-images.githubusercontent.com/1128750/128943496-d182ef1b-bfde-43f6-aec8-1e01c60408e4.png)

#### Settings

![image](https://user-images.githubusercontent.com/1128750/128943522-53dbff39-16dd-4da2-88e1-66e98003ed68.png)

#### IDE version

<img width="441" alt="Screen Shot 2021-08-10 at 3 31 36 PM" src="https://user-images.githubusercontent.com/1128750/128943366-f6155267-21aa-4432-a4c1-f95c6c1e1a5c.png">

**Comment by abrookins** [comment] 2021-08-10 22:55
Interesting. @mgartner I couldn't reproduce.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/97182/128945038-8c9f5519-049a-4087-a99b-4ce37e44c611.png">

However, can you check if you have a custom right margin override setting?

<img width="995" alt="Screen Shot 2021-08-10 at 3 50 51 PM" src="https://user-images.githubusercontent.com/97182/128945071-8f363e58-20bb-4ac6-bfa5-89cdfd275294.png">

The plugin honors that override if it's present.

**Comment by mgartner** [comment] 2021-08-10 22:57
I do have it set, but also at 80:

![image](https://user-images.githubusercontent.com/1128750/128945325-152e0050-16a4-4ff8-8c2e-c7e71e6a9fed.png)

**Comment by MarkCButler** [comment] 2021-08-10 23:11
The problem may specific to certain platforms.

I am using the plugin with PyCharm on two systems, one running Windows and the other running Pop!_OS (similar to Ubuntu).  When I updated the plugin today on both systems, there were no problems on Pop!_OS, but on Windows, the wrapped text extended past column 80 (perhaps wrapping to column 100).  I couldn't find any relevant difference in the PyCharm settings on the two system.  In particular, both had the hard wrap set at 80.

On the Windows system, setting the right margin override to 80 didn't change the behavior.  (Before today I have never tried the right margin override--instead I have just had the hard wrap set to 80.)

**Comment by abrookins** [comment] 2021-08-10 23:34
Well, that's interesting. I'll try to reproduce on Windows!

**Comment by mgartner** [comment] 2021-08-10 23:47
FWIW, I'm running macOS 11.5.

**Comment by abrookins** [comment] 2021-08-11 03:47
👍 I was able to reproduce on a Mac and am looking at it now.

**Comment by JeffreyStevens** [comment] 2021-08-11 11:40
I will say I also see this problem on my 11.5 Mac as well.

**Comment by jaredbeck** [comment] 2021-08-11 21:01
Can confirm, after updating from `1.4` to to `1.6.0-SNAPSHOT`, on macOS 11.4, the plugin no longer respects the "Right margin override" setting when wrapping JS comments that use the `//` operator.  Wrapping _does_ occur, but the margin setting is not respected.

**Comment by abrookins** [comment] 2021-08-12 08:53
Should be fixed in 1.7.0, now published to the Plugins Marketplace.

**Closed by abrookins** 2021-08-12 08:53 UTC

**Comment by MarkCButler** [comment] 2021-08-12 14:42
The problem is resolved on my Windows system.  Thank you so much!  This plugin makes a huge difference in my daily work.

**Comment by mgartner** [comment] 2021-08-12 16:31
Thanks @abrookins!!!

**Comment by irfansharif** [comment] 2021-08-12 18:31
Thanks @abrookins! I've been living in the dark ages these past few weeks.
